const Strings = {
    SelectUser: 'Select user type',
    User: 'User',
    UserDescription: 'They looking for care-taker. User can be a parents or anyone who need help.',
    HomeCare: 'Home care',
    HomeCareDescription: 'Home care includes any professional support services that allow a person to live safely in their home.',
    Continue: 'Continue',
    Skip: 'Skip',
    BoardingTitleOne: 'An environment for your child',
    BoardingOneDescription: 'A positive environment encourages the holistic development of all children. The physical environment affects how children learn and develop.',
    BoardingTitleTwo: 'An environment for elderly people',
    BoardingTwoDescription: 'The care of older people who need help with medical problems or everyday tasks.',
    BoardingTitleThree: 'Find the right home care giver for you',
    BoardingThreeDescription: 'Home care is care that allows a person with special needs to stay in their home. It might be for people who are getting help.',
    BoardingTitleFour: 'An ideal Babysitter',
    BoardingFourDescription: 'An ideal babysitter is one that can balance both sides, keeping both children and parents happy and meeting the expectations of both.',
    BoardingTitleFive: 'Home care support services',
    BoardingFiveDescription: 'Home care includes any professional support services that allow a person to live safely in their home.',
    WelcomeTitle: 'Welcome to OurVilla',
    WelcomeDescription: 'Use your credentials below and sign in to your account',
    Email: 'Email',
    Password: 'Password',
    ForgotPassword: 'Forgot password?',
    ForgotPasswordDescription: 'Don’t worry! It’s happens. Please enter the address associated with your account.',
    SignIn: 'Sign In',
    SignUp: 'Sign Up',
    ContinueWith: 'or continue with',
    HaveAccount: 'Don’t have an account?',
    FirstName: 'First name',
    LastName: 'Last name',
    ConfirmPassword: 'Confirm password',
    UploadProof: 'Upload ID proof',
    CheckmarkDescription: 'I wanted to be able to give single moms/dads to work and bring their kids with them to work.',
    SendOTP: 'Send OTP',
    VerifyOTP: 'Verify OTP',
    EnterOTP: 'Enter OTP',
    EnterOTPDescription: 'Enter the verification code we just sent you on your email address.',
    NewPassword: 'New password',
    NewPasswordDescription: 'Please enter your new password below.',
    Save: 'Save',
    BookNow: 'Book Now',
    Payment: 'Payment',
    ConfirmPayment: 'Confirm Payment',
    GetStart: 'Get Start',
    CreateAccount: 'Create an account',
    uploadTitle: 'Click here to upload',
    sizeLimit: 'Maximum size : 2mb',
    DateBirth: 'Date of birth',
    Address: 'Address',
    About: 'About',
    SelectLocation: 'Select location',
    AtHome: 'At home',
    AtBabySitters: 'At babysitter’s',
    UploadProfile: 'Upload profile',
    Confirm: 'Confirm',
    Booking: 'Booking',
    AddCategory: 'Add category',
    CategoryDetails: 'Add children details',
    Morning: 'Good morning',
    UserName: 'Phillip Carder',
    Setting: 'Setting',
    DrivingLicense: 'Driving license verification',
    Instructions: 'Instructions.',
    DrivingLicenseDescription: 'Make sure your driver’s license is not expired and avoid using flash so, that the information is clear and visible.',
    EducationCertificates: 'Education Certificates',
    UploadEducationCertificates: 'Upload your education certificates here.',
    GovernmentDocuments: 'Government documents',
    GovernmentDocumentsDescription: 'Upload a current document from the list below to verify that you can legally work as an independent contractor in canada.',
    ForExp: 'For example :-',
    IDProof: 'ID proof',
    AddressProof: 'address proof',
    PassportProof: 'passport, etc.',
    NextAppointments: 'Next appointments',
    Cancel: 'Cancel',
    Accept: 'Accept',
    RecentlyProfile: 'Recently shown your profile',
    Children: 'Children',
    Day: 'day',
    UpcomingBooking: 'Upcoming booking',
    location: 'D-102, Montreal, Canada',
    PhillipCarderMira: 'Phillip Carder Mira',
    Profile: 'Profile',
    Account: 'Account',
    Notification: 'Notification',
    CustomerSupport: 'Customer support',
    UpgradePremium: 'Upgrade to premium',
    TermsConditions: 'Terms & Conditions',
    PrivacyPolicy: 'Privacy policy',
    LogOut: 'Log Out',
    ProfilePhoto: 'Profile Photo',
    ProfileDescription: 'Your profile photo helps people recognize you. please note that once you submit your profile photo it cannot be changed.',
    ProfileDescriptionOne: '1. Face the camera directly with your eyes and mouth clearly visible.',
    ProfileDescriptionTwo: '2. Make sure the photo is well lit, free of glare, and in focus.',
    ProfileDescriptionThree: '3. No photos of a photo, filter, or alterations',
    ApprovedDocuments: 'Approved documents',
    ABACertificate: 'ABA certificate',
    ABICertificate: 'ABI certificate',
    SubmittedDocuments: 'Submitted documents',
    PendingDocuments: 'Pending documents',
    DrivingLicenses: 'Driving license',
    EarlyChildhoodEducation: 'Early childhood education',
    ListEmpty: 'List empty',
    Add: 'Add',
    ResendOTP: 'Resend OTP in',
    Boy: 'Boy',
    Years: 'years',
    PhillipCarder: 'Phillip Carder',
    ViewCategoryDetails: 'He is very creative and he loves art.',
    Age: 'Age',
    Gender: 'Gender',
    Education: 'Education',
    MedicalCondition: 'Medical condition',
    OtherDetails: 'Other details',
    Optional: '(Optional)',
    Skills: 'Skills',
    Feedback: 'Feedback',
    UserDetails: 'I have a lot of experience working with infants and toddlers, and I also spent three years babysitting a six-year-old girl on the autism spectrum. I truly love working with young kids, and I approach each child as an individual who I get to help grow and teach.',
    Dance: 'Dance',
    Music: 'Music',
    Drawing: 'Drawing',
    Crafting: 'Crafting',
    Games: 'Games',
    Cooking: 'Cooking',
    Certificates: 'Certificates',
    ViewAll: 'ViewAll',
    pdf: 'pdf',
    DavisCarder: 'Davis Carder',
    DavisCarderAbout: 'He is a fantastic nanny for both my girls for almost 10 months. She is responsible, caring...',
    JohnsonGreen: 'Johnson Green',
    JohnsonGreenAbout: 'Absolutely amazing experience! Babysitter Johnson Green took great care of our...',
    SmithFlores: 'Smith Flores',
    SmithFloresAbout: 'We were a bit nervous since it had been so long since we had used a sitter because of...',
    DaysAgo: 'days ago',
    BookingDetails: 'Booking Details',
    CurrentLocation: 'Current Location',
    Filter: 'Filter',
    ClearAll: 'Clear all',
    ExperienceBabysitter: 'Experience of babysitter',
    VerificationDocuments: 'Verification documents',
    AgeBabysitter: 'Age of babysitter',
    Availability: 'Availability',
    MaximumRatePerHour: 'Maximum rate per hour',
    Phone: 'Phone',
    BecomeHomeCare: 'Become Home Care',
    BecomeUser: 'Become a User',
    ForgetPasswordMsg: 'OTP send successfully. please check your email!',
    ResetPasswordMsg: 'Your password has been changed successfully.',
    RegisterMsg: 'Congratulations, Your account has been successfully created.',
    CreatePersonMsg: 'Congratulations, Details Added successfully.',
    AppointmentBook: 'Congratulations, Your Appointment is book successfully.',
    LoginMsg: 'You have successfully logged in.',
    TakePhoto: 'Take photo',
    ChooseGallery: 'Choose from gallery',
    ChooseDocument: 'Choose from document file',
    SelectGender: 'Select Gender',
    PhoneNumber: 'Phone Number'
}

export default Strings;